
# Look for the header file.
FIND_PATH(WIRINGPI_INCLUDE_DIR NAMES softPwm.h)

# Look for the library.
FIND_LIBRARY(WIRINGPI_LIBRARY NAMES WIRINGPI wiringPi)

# Handle the QUIETLY and REQUIRED arguments and set WIRINGPI_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(WIRINGPI DEFAULT_MSG WIRINGPI_LIBRARY WIRINGPI_INCLUDE_DIR)

# Copy the results to the output variables.
IF(WIRINGPI_FOUND)
        SET(WIRINGPI_LIBRARIES ${WIRINGPI_LIBRARY} )
        SET(WIRINGPI_INCLUDE_DIRS ${WIRINGPI_INCLUDE_DIR})
ELSE(WIRINGPI_FOUND)
        SET(WIRINGPI_LIBRARIES)
        SET(WIRINGPI_INCLUDE_DIRS)
ENDIF(WIRINGPI_FOUND)

MARK_AS_ADVANCED(WIRINGPI_INCLUDE_DIRS WIRINGPI_LIBRARIES)
