
# Look for the header file.
FIND_PATH(TNTNET_INCLUDE_DIR NAMES tnt/tntnet.h)

# Look for the library.
FIND_LIBRARY(TNTNET_LIBRARY NAMES tntnet cxxtools)

# Handle the QUIETLY and REQUIRED arguments and set TNTNET_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TNTNET DEFAULT_MSG TNTNET_LIBRARY TNTNET_INCLUDE_DIR)

# Copy the results to the output variables.
IF(TNTNET_FOUND)
        SET(TNTNET_LIBRARIES ${TNTNET_LIBRARY})
        SET(TNTNET_INCLUDE_DIRS ${TNTNET_INCLUDE_DIR})
ELSE(TNTNET_FOUND)
        SET(TNTNET_LIBRARIES)
        SET(TNTNET_INCLUDE_DIRS)
ENDIF(TNTNET_FOUND)

MARK_AS_ADVANCED(TNTNET_INCLUDE_DIRS TNTNET_LIBRARIES)
